name: cargaliberada
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.1.0 
  get: ^4.7.2
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  sqflite: ^2.4.2
  google_sign_in: ^6.2.2
  shared_preferences: ^2.5.3
  sqflite_common_ffi: ^2.3.6
  sqflite_common_ffi_web: ^1.0.1+1
  crypto: ^3.0.3
  path_provider: ^2.1.1
  image_picker: ^1.0.4
  googleapis: ^11.4.0  
  googleapis_auth: ^1.4.1
  table_calendar: ^3.0.9  
  path: ^1.9.0
  font_awesome_flutter: ^10.8.0
  sqlite3: ^2.5.0
  sqlite3_flutter_libs: ^0.5.27
  flutter_masked_text2: ^0.9.1
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - lib/img/
    - assets/
    - assets/icons/
    - assets/icons/google.png
    - assets/images/
